sugarcube-2:
  macros:
    timerDebug:
      name: timerDebug
    gameStart:
      name: gameStart
    golemPopCounter:
      name: golemPopCounter
    golemPopBar:
      name: golemPopBar
      container: true
