sugarcube-2:
  macros:
    timerDebug:
      name: timerDebug
    gameStart:
      name: gameStart
    golemPopCounter:
      name: golemPopCounter
    golemPopBar:
      name: golemPopBar
      container: true
    resourceCounter:
      name: resourceCounter
    resourceBar:
      name: resourceBar
      container: true
    resourceWorkerControl:
      name: resourceWorkerControl
    golemAvailableCounter:
      name: golemAvailableCounter
    resourceWorkerCounter:
      name: resourceWorkerCounter
    hubMap:
      name: hubMap
    buyBuildingControl:
      name: buyBuildingControl
      container: true
    findResourceAction:
      name: findResourceAction
    gatherResourceAction:
      name: gatherResourceAction
    deskList:
      name: deskList
    deskCommands:
      name: deskCommands
