sugarcube-2:
  macros:
    timerDebug:
      name: timerDebug
    gameStart:
      name: gameStart
    golemPopCounter:
      name: golemPopCounter
    golemPopBar:
      name: golemPopBar
      container: true
    tierOneResourceCounter:
      name: tierOneResourceCounter
    tierOneResoureBar:
      name: tierOneResoureBar
      container: true
    tierOneWorkerControl:
      name: tierOneWorkerControl
    golemAvailableCounter:
      name: golemAvailableCounter
    tierOneWorkerCounter:
      name: tierOneWorkerCounter
    hubMap:
      name: hubMap
